# Generated by Django 3.1.4 on 2020-12-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20201226_1054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='medida',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='city',
            new_name='medida',
        ),
    ]
