# Generated by Django 3.1.4 on 2020-12-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_auto_20201226_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_de_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
