# Generated by Django 3.1.4 on 2020-12-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_produto_data_de_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='name',
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=5),
        ),
    ]
